Target.module(
  name: "CodeCompletionService",
  dependencies: [
    "AccessibilityFoundation",
    "AppFoundation",
    "ChatAppEvents",
    "CodeCompletionFoundation",
    "CodeCompletionServiceInterface",
    "ConcurrencyFoundation",
    "DependencyFoundation",
    "FileDiffFoundation",
    "SettingsServiceInterface",
    "XcodeObserverServiceInterface",
  ],
  testsDependencies: [
    "AccessibilityFoundation",
    "AppFoundation",
    "CodeCompletionFoundation",
    "CodeCompletionService",
    "CodeCompletionServiceInterface",
    "ConcurrencyFoundation",
    "FileDiffFoundation",
    "SettingsServiceInterface",
    "SwiftTesting",
    "ThreadSafe",
    "XcodeObserverServiceInterface",
  ])
