// swift-tools-version: 6.2
// The swift-tools-version declares the minimum version of Swift required to build this package.

// Package.swift is generated by running ./app/tools/dependencies/sync.sh. DO NOT MODIFY DIRECTLY.
// Local dependencies are automatically identified.
// 3rd party dependencies are manually added to the corresponding Module.swift files.
// New 3rd party dependencies should be added to Package.template.swift first.

import CompilerPluginSupport
import PackageDescription

extension Target {
  static func module(
    name: String,
    dependencies: [Target.Dependency],
    resources: [PackageDescription.Resource]? = nil,
    interfaceDependencies: [Target.Dependency]? = nil,
    interfaceTestDependencies: [Target.Dependency]? = nil,
    testDependencies: [Target.Dependency]? = nil,
    testExclude: [String] = [],
    testResources: [PackageDescription.Resource]? = nil,
    path: String)
    -> [Target]
  {
    var targets = [Target]()
    var extraDependencies = [Target.Dependency]()

    // Interface target and its dependencies should be added to all targets
    if let interfaceDependencies {
      let interfaceTarget = Target.target(
        name: "\(name)Interface",
        dependencies: interfaceDependencies,
        path: "\(path)/Interface")
      targets.append(interfaceTarget)
      extraDependencies.append(Target.Dependency.byName(name: "\(name)Interface"))

      // Interface test target if interfaceTestDependencies is provided
      if let interfaceTestDependencies {
        let interfaceTestTarget = Target.testTarget(
          name: "\(name)InterfaceTests",
          dependencies: interfaceTestDependencies + interfaceDependencies + [Target.Dependency.byName(name: "\(name)Interface")],
          path: "\(path)/Interface/Tests")
        targets.append(interfaceTestTarget)
      }
    }

    // Main target with its dependencies + interface
    let sourceTarget = Target.target(
      name: name,
      dependencies: dependencies + extraDependencies,
      path: "\(path)/Sources",
      resources: resources,
      swiftSettings: [
        .unsafeFlags(["-Xfrontend", "-disable-availability-checking"]),
      ])
    targets.append(sourceTarget)
    extraDependencies.append(Target.Dependency.byName(name: name))

    // Main test target with its dependencies + main target + interface
    if let testDependencies {
      let testTarget = Target.testTarget(
        name: "\(name)Tests",
        dependencies: testDependencies + extraDependencies,
        path: "\(path)/Tests",
        exclude: testExclude,
        resources: testResources)
      targets.append(testTarget)
    }
    return targets
  }

  static func macroModule(
    name: String,
    dependencies: [Target.Dependency],
    macroDependencies: [Target.Dependency] = [],
    testDependencies: [Target.Dependency]? = nil,
    path: String)
    -> [Target]
  {
    let pluginTarget = Target.target(
      name: name,
      dependencies: dependencies,
      path: "\(path)/Sources")
    let macroTarget = Target.macro(
      name: "\(name)Macro",
      dependencies: macroDependencies,
      path: "\(path)/Macro")
    if let testDependencies {
      let testTarget = Target.testTarget(
        name: "\(name)Tests",
        dependencies: testDependencies + [Target.Dependency.byName(name: name)],
        path: "\(path)/Tests")
      return [pluginTarget, macroTarget, testTarget]
    } else {
      return [pluginTarget, macroTarget]
    }
  }
}

var targets = [Target]()

let package = Package(
  name: "Packages",
  platforms: [
    .macOS("15.2"),
  ],
  products: [],
  dependencies: [],
  targets: targets)
