Target.module(
  name: "ExecuteCommandTool",
  dependencies: [
    .product(name: "Dependencies", package: "swift-dependencies"),
    "AppFoundation",
    "CodePreview",
    "ConcurrencyFoundation",
    "DLS",
    "JSONFoundation",
    "LocalServerServiceInterface",
    "ShellServiceInterface",
    "ThreadSafe",
    "ToolFoundation",
    "ToolTypesFoundation",
  ],
  testsDependencies: [
    .product(name: "Dependencies", package: "swift-dependencies"),
    "AppFoundation",
    "ConcurrencyFoundation",
    "ExecuteCommandTool",
    "LocalServerServiceInterface",
    "ShellServiceInterface",
    "SwiftTesting",
    "ToolFoundation",
  ])
