Target.module(
  name: "CodeCompletionFeature",
  dependencies: [
    .product(name: "Dependencies", package: "swift-dependencies"),
    "AccessibilityFoundation",
    "AccessibilityObjCFoundation",
    "CodeCompletionFoundation",
    "CodeCompletionServiceInterface",
    "ConcurrencyFoundation",
    "DLS",
    "FileDiffTypesFoundation",
    "FoundationInterfaces",
    "KeyboardShortcutServiceInterface",
    "LoggingServiceInterface",
    "RoutingFoundation",
    "SettingsServiceInterface",
    "ShellServiceInterface",
    "XcodeControllerServiceInterface",
    "XcodeObserverServiceInterface",
    "XcodeObserverWindowsAdapter",
    "XcodeThemeFoundation",
  ])
