Target.module(
  name: "SettingsService",
  dependencies: [
    "AppFoundation",
    "ConcurrencyFoundation",
    "DependencyFoundation",
    "FoundationInterfaces",
    "JSONFoundation",
    "LLMFoundation",
    "LoggingServiceInterface",
    "SettingsServiceInterface",
    "SharedValuesFoundation",
    "ThreadSafe",
  ],
  testsDependencies: [
    "ConcurrencyFoundation",
    "FoundationInterfaces",
    "LLMFoundation",
    "SettingsService",
    "SettingsServiceInterface",
    "SharedValuesFoundation",
    "SwiftTesting",
  ],
  interfaceDependencies: [
    .product(name: "Dependencies", package: "swift-dependencies"),
    "AppFoundation",
    "ConcurrencyFoundation",
    "JSONFoundation",
    "LLMFoundation",
    "LoggingServiceInterface",
  ],
  interfaceTestsDependencies: [
    "LLMFoundation",
    "SettingsServiceInterface",
    "SwiftTesting",
  ])
