import fs from "fs"
import { generateJSONSchemas } from "./schema-generation/tsToJSONSchema"
import { generateSwiftSchema } from "./schema-generation/jsonSchemaToSwift"
import { join, dirname } from "path"

import { fileURLToPath } from "url"
import { toPascalCase } from "./schema-generation/utils"

const __dirname = dirname(fileURLToPath(import.meta.url))

const generate = () => {
	const jsonSchemas = generateJSONSchemas({
		path: "./src/server/schemas",
	})
	for (const { name, schema: jsonSchema, destination, schemaName } of jsonSchemas) {
		const swiftSchema = generateSwiftSchema(jsonSchema, name, schemaName)

		const rootDir = join(__dirname, "../..")
		const destinationPath = join(rootDir, destination)

		fs.writeFileSync(destinationPath, swiftSchema)
		fs.writeFileSync(
			join(dirname(destinationPath), `${toPascalCase(schemaName)}.generated.swift`),
			`// swiftformat:disable all
// This file is generated by \`yarn export-schema-swift\`.
// Do not edit it manually.

import Foundation
import JSONFoundation

public enum ${schemaName} {}

extension KeyedDecodingContainer {
  /// Sugar syntax for decoding optional values without changing the type to be non optional.
  func decodeIfPresent<T: Decodable>(_ type: T?.Type, forKey key: KeyedDecodingContainer<K>.Key) throws -> T? {
    if contains(key) {
      return try decode(type, forKey: key)
    }
    return nil
  }
}
`,
		)
	}
}

generate()

export default generate
