// swift-tools-version: 6.2
// The swift-tools-version declares the minimum version of Swift required to build this package.

// Package.swift is generated by running ./app/tools/dependencies/sync.sh. DO NOT MODIFY DIRECTLY.
// Local dependencies are automatically identified.
// 3rd party dependencies are manually added to the corresponding Module.swift files.
// New 3rd party dependencies should be added to Package.template.swift first.

import CompilerPluginSupport
import PackageDescription

extension Target {
  static func module(
    name: String,
    dependencies: [Target.Dependency]? = nil,
    resources: [PackageDescription.Resource]? = nil,
    testsDependencies: [Target.Dependency]? = nil,
    testsExclude: [String] = [],
    testsResources: [PackageDescription.Resource]? = nil,
    interfaceDependencies: [Target.Dependency]? = nil,
    interfaceTestsDependencies: [Target.Dependency]? = nil,
    interfaceTestsResources: [PackageDescription.Resource]? = nil,
    path: String)
    -> [Target]
  {
    var targets = [Target]()
    guard let dependencies else { return [] }

    targets.append(
      Target.target(
        name: name,
        dependencies: dependencies,
        path: "\(path)/Sources",
        resources: resources,
        swiftSettings: [
          .unsafeFlags(["-Xfrontend", "-disable-availability-checking"]),
        ]))

    if let testsDependencies {
      targets.append(
        Target.testTarget(
          name: "\(name)Tests",
          dependencies: testsDependencies,
          path: "\(path)/Tests",
          exclude: testsExclude,
          resources: testsResources))
    }

    // Interface target
    if let interfaceDependencies {
      targets.append(
        Target.target(
          name: "\(name)Interface",
          dependencies: interfaceDependencies,
          path: "\(path)/InterfaceSources"))
    }

    // Interface test target
    if let interfaceTestsDependencies {
      targets.append(
        Target.testTarget(
          name: "\(name)InterfaceTests",
          dependencies: interfaceTestsDependencies,
          path: "\(path)/InterfaceTests",
          resources: interfaceTestsResources))
    }
    return targets
  }

  static func macroModule(
    name: String,
    macroDependencies: [Target.Dependency] = [],
    dependencies: [Target.Dependency],
    testsDependencies: [Target.Dependency]? = nil,
    path: String)
    -> [Target]
  {
    let macroTarget = Target.macro(
      name: "\(name)Macro",
      dependencies: macroDependencies,
      path: "\(path)/Macro")
    let pluginTarget = Target.target(
      name: name,
      dependencies: dependencies + [Target.Dependency.byName(name: "\(name)Macro")],
      path: "\(path)/Sources")
    if let testsDependencies {
      let testTarget = Target.testTarget(
        name: "\(name)Tests",
        dependencies: testsDependencies + [Target.Dependency.byName(name: name)],
        path: "\(path)/Tests")
      return [pluginTarget, macroTarget, testTarget]
    } else {
      return [pluginTarget, macroTarget]
    }
  }
}

var targets = [Target]()

let package = Package(
  name: "Packages",
  platforms: [
    .macOS("15.0"),
  ],
  products: [
    .library(
      name: "App",
      targets: [
        "App",
      ]),
    .library(
      name: "AppExtension",
      targets: [
        "AppExtension",
      ]),
    .library(
      name: "AppLauncher",
      targets: [
        "AppLauncher",
      ]),
  ],
  dependencies: [
    .package(url: "https://github.com/appstefan/highlightswift", from: "1.1.0"),
    .package(
      url: "https://github.com/gsabran/Down",
      revision: "14309dd8781c7613063344727454ffbbebc8e8bd"),
    .package(url: "https://github.com/pointfreeco/swift-dependencies", from: "1.9.0"),
    .package(url: "https://github.com/sindresorhus/KeyboardShortcuts", from: "2.2.4"),
    .package(url: "https://github.com/tuist/XcodeProj", from: "9.1.0"),
    .package(url: "https://github.com/ukushu/Ifrit", from: "3.0.0"),
    .package(url: "https://github.com/swiftlang/swift-syntax", from: "602.0.0"),
    .package(url: "https://github.com/getsentry/sentry-cocoa", from: "8.56.0"),
    .package(url: "https://github.com/statsig-io/statsig-kit", from: "1.53.5"),
    .package(url: "https://github.com/sparkle-project/Sparkle", from: "2.7.0"),
    .package(
      url: "https://github.com/swiftlang/swift-subprocess",
      revision: "43f99d981c7486858b4bcb8cb5861e63bd63d841"),
    .package(url: "https://github.com/vapor/vapor.git", from: "4.115.1"),
    .package(url: "https://github.com/gsabran/JSONScanner", from: "1.0.0"),
    .package(url: "https://github.com/MobileNativeFoundation/XCLogParser", from: "0.2.41"),
    .package(url: "https://github.com/groue/GRDB.swift", from: "7.5.0"),
    .package(url: "https://github.com/bugsnag/bugsnag-cocoa", from: "6.32.2"),
    .package(url: "https://github.com/modelcontextprotocol/swift-sdk", from: "0.10.1"),
    .package(url: "https://github.com/scinfu/SwiftSoup.git", from: "2.11.1"),

    // Testing dependencies:
    .package(url: "https://github.com/pointfreeco/swift-snapshot-testing", from: "1.18.7"),
    .package(url: "https://github.com/pointfreeco/swift-macro-testing", from: "0.6.4"),
  ],
  targets: targets)
