// This file is generated. Do not modify directly.

// swift-tools-version: 6.2
// The swift-tools-version declares the minimum version of Swift required to build this package.

// Package.swift is generated by running ./app/tools/dependencies/sync.sh. DO NOT MODIFY DIRECTLY.
// Local dependencies are automatically identified.
// 3rd party dependencies are manually added to the corresponding Module.swift files.
// New 3rd party dependencies should be added to Package.template.swift first.

import CompilerPluginSupport
import PackageDescription

extension Target {
  static func module(
    name: String,
    dependencies: [Target.Dependency]? = nil,
    resources: [PackageDescription.Resource]? = nil,
    testsDependencies: [Target.Dependency]? = nil,
    testsExclude: [String] = [],
    testsResources: [PackageDescription.Resource]? = nil,
    interfaceDependencies: [Target.Dependency]? = nil,
    interfaceTestsDependencies: [Target.Dependency]? = nil,
    interfaceTestsResources: [PackageDescription.Resource]? = nil,
    path: String)
    -> [Target]
  {
    var targets = [Target]()
    guard let dependencies else { return [] }

    targets.append(
      Target.target(
        name: name,
        dependencies: dependencies,
        path: "\(path)/Sources",
        resources: resources,
        swiftSettings: [
          .unsafeFlags(["-Xfrontend", "-disable-availability-checking"]),
        ]))

    if let testsDependencies {
      targets.append(
        Target.testTarget(
          name: "\(name)Tests",
          dependencies: testsDependencies,
          path: "\(path)/Tests",
          exclude: testsExclude,
          resources: testsResources))
    }

    // Interface target
    if let interfaceDependencies {
      targets.append(
        Target.target(
          name: "\(name)Interface",
          dependencies: interfaceDependencies,
          path: "\(path)/InterfaceSources"))
    }

    // Interface test target
    if let interfaceTestsDependencies {
      targets.append(
        Target.testTarget(
          name: "\(name)InterfaceTests",
          dependencies: interfaceTestsDependencies,
          path: "\(path)/InterfaceTests",
          resources: interfaceTestsResources))
    }
    return targets
  }

  static func macroModule(
    name: String,
    macroDependencies: [Target.Dependency] = [],
    dependencies: [Target.Dependency],
    testsDependencies: [Target.Dependency]? = nil,
    path: String)
    -> [Target]
  {
    let macroTarget = Target.macro(
      name: "\(name)Macro",
      dependencies: macroDependencies,
      path: "\(path)/Macro")
    let pluginTarget = Target.target(
      name: name,
      dependencies: dependencies + [Target.Dependency.byName(name: "\(name)Macro")],
      path: "\(path)/Sources")
    if let testsDependencies {
      let testTarget = Target.testTarget(
        name: "\(name)Tests",
        dependencies: testsDependencies + [Target.Dependency.byName(name: name)],
        path: "\(path)/Tests")
      return [pluginTarget, macroTarget, testTarget]
    } else {
      return [pluginTarget, macroTarget]
    }
  }
}

var targets = [Target]()

targets.append(
  contentsOf: Target.module(
    name: "AccessibilityFoundation",
    dependencies: [
      "LoggingServiceInterface",
    ],
    testsDependencies: [
      "AccessibilityFoundation",
    ],
    path: "./foundations/AccessibilityFoundation"))

targets.append(
  contentsOf: Target.module(
    name: "AccessibilityObjCFoundation",
    dependencies: [],
    path: "./foundations/AccessibilityObjCFoundation"))

targets.append(
  contentsOf: Target.module(
    name: "ACPTool",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "CodePreview",
      "ConcurrencyFoundation",
      "DLS",
      "FileDiffFoundation",
      "JSONFoundation",
      "LoggingServiceInterface",
      "Markdown",
      "ThreadSafe",
      "ToolFoundation",
      "ToolTypesFoundation",
      "ToolUI",
      "XcodeControllerServiceInterface",
    ],
    path: "./plugins/tools/ACPTool"))

targets.append(
  contentsOf: Target.module(
    name: "App",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      .product(name: "KeyboardShortcuts", package: "KeyboardShortcuts"),
      "AccessibilityFoundation",
      "AccessibilityObjCFoundation",
      "ACPTool",
      "AppEventService",
      "AppEventServiceInterface",
      "AppFoundation",
      "AppUpdateService",
      "AppUpdateServiceInterface",
      "AskFollowUpTool",
      "BuildTool",
      "ChatAppEvents",
      "ChatCompletionService",
      "ChatCompletionServiceInterface",
      "ChatFeature",
      "ChatHistoryServiceInterface",
      "ChatService",
      "ChatServiceInterface",
      "CheckpointService",
      "CheckpointServiceInterface",
      "ClaudeCodeTools",
      "CodeCompletionFeature",
      "CodeCompletionFoundation",
      "CodeCompletionService",
      "CodeCompletionServiceInterface",
      "ConcurrencyFoundation",
      "DefaultToolView",
      "DependencyFoundation",
      "DLS",
      "EditFilesTool",
      "ExecuteCommandTool",
      "ExtensionCommandHandler",
      "FileSuggestionService",
      "FileSuggestionServiceInterface",
      "FoundationInterfaces",
      "GithubCopilotFeature",
      "GithubCopilotService",
      "GithubCopilotServiceInterface",
      "HighlighterServiceInterface",
      "JRPCService",
      "JRPCServiceInterface",
      "KeyboardShortcutService",
      "KeyboardShortcutServiceInterface",
      "LLMService",
      "LLMServiceInterface",
      "LocalServerService",
      "LocalServerServiceInterface",
      "LoggingService",
      "LoggingServiceInterface",
      "LSTool",
      "MCPService",
      "MCPServiceInterface",
      "Onboarding",
      "PermissionsService",
      "PermissionsServiceInterface",
      "PushNotificationService",
      "PushNotificationServiceInterface",
      "ReadFileTool",
      "RoutingFoundation",
      "SearchFilesTool",
      "SettingsFeature",
      "SettingsFeatureInterface",
      "SettingsService",
      "SettingsServiceInterface",
      "ShellService",
      "ShellServiceInterface",
      "ThreadSafe",
      "ToolFoundation",
      "WebFetchTool",
      "XcodeControllerService",
      "XcodeControllerServiceInterface",
      "XcodeObserverService",
      "XcodeObserverServiceInterface",
      "XcodeObserverWindowsAdapter",
      "XPCServiceInterface",
    ],
    resources: [],
    testsDependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      .product(name: "KeyboardShortcuts", package: "KeyboardShortcuts"),
      "App",
      "AppEventServiceInterface",
      "ChatAppEvents",
      "ChatFoundation",
      "ConcurrencyFoundation",
      "FoundationInterfaces",
      "PermissionsServiceInterface",
      "SettingsServiceInterface",
      "SharedValuesFoundation",
      "SwiftTesting",
    ],
    path: "./App"))

targets.append(
  contentsOf: Target.module(
    name: "AppEventService",
    dependencies: [
      "AppEventServiceInterface",
      "DependencyFoundation",
      "LoggingServiceInterface",
      "ThreadSafe",
    ],
    path: "./services/AppEventService"))

targets.append(
  contentsOf: Target.module(
    name: "AppEventServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "ConcurrencyFoundation",
    ],
    path: "./serviceInterfaces/AppEventServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "AppExtension",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AccessibilityFoundation",
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "ExtensionEventsInterface",
      "FileDiffFoundation",
      "FileDiffTypesFoundation",
      "FoundationInterfaces",
      "LoggingService",
      "LoggingServiceInterface",
      "SettingsService",
      "SettingsServiceInterface",
      "SharedUtilsFoundation",
      "SharedValuesFoundation",
      "ThreadSafe",
    ],
    path: "./AppExtension"))

targets.append(
  contentsOf: Target.module(
    name: "AppFoundation",
    dependencies: [],
    testsDependencies: [
      "AppFoundation",
    ],
    path: "./foundations/AppFoundation"))

targets.append(
  contentsOf: Target.module(
    name: "AppLauncher",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "DependencyFoundation",
      "FoundationInterfaces",
      "LoggingService",
      "LoggingServiceInterface",
      "SharedUtilsFoundation",
      "ThreadSafe",
      "XPCServiceInterface",
    ],
    path: "./AppLauncher"))

targets.append(
  contentsOf: Target.module(
    name: "AppUpdateService",
    dependencies: [
      .product(name: "Sparkle", package: "Sparkle"),
      "AppFoundation",
      "AppUpdateServiceInterface",
      "DependencyFoundation",
      "FoundationInterfaces",
      "LoggingServiceInterface",
      "SettingsServiceInterface",
      "ThreadSafe",
    ],
    testsDependencies: [],
    path: "./services/AppUpdateService"))

targets.append(
  contentsOf: Target.module(
    name: "AppUpdateServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "ConcurrencyFoundation",
      "ThreadSafe",
    ],
    testsDependencies: [
      "AppUpdateServiceInterface",
      "SwiftTesting",
    ],
    path: "./serviceInterfaces/AppUpdateServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "AskFollowUpTool",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "ConcurrencyFoundation",
      "DLS",
      "JSONFoundation",
      "LocalServerServiceInterface",
      "ToolFoundation",
    ],
    testsDependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "AskFollowUpTool",
      "SwiftTesting",
      "ToolFoundation",
    ],
    path: "./plugins/tools/AskFollowUpTool"))

targets.append(
  contentsOf: Target.module(
    name: "BuildTool",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "ConcurrencyFoundation",
      "DLS",
      "JSONFoundation",
      "LocalServerServiceInterface",
      "ToolFoundation",
      "XcodeControllerServiceInterface",
    ],
    testsDependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "BuildTool",
      "SwiftTesting",
      "ToolFoundation",
      "XcodeControllerServiceInterface",
    ],
    path: "./plugins/tools/BuildTool"))

targets.append(
  contentsOf: Target.module(
    name: "ChatAppEvents",
    dependencies: [
      "AppEventServiceInterface",
      "ChatFoundation",
    ],
    path: "./foundations/ChatAppEvents"))

targets.append(
  contentsOf: Target.module(
    name: "ChatCompletionService",
    dependencies: [
      .product(name: "Vapor", package: "vapor"),
      "AppFoundation",
      "ChatCompletionServiceInterface",
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "FoundationInterfaces",
      "JSONFoundation",
      "LLMServiceInterface",
      "LoggingServiceInterface",
      "SettingsServiceInterface",
      "ThreadSafe",
    ],
    testsDependencies: [
      "AppFoundation",
      "ChatCompletionService",
    ],
    path: "./services/ChatCompletionService"))

targets.append(
  contentsOf: Target.module(
    name: "ChatCompletionServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "LocalServerServiceInterface",
    ],
    path: "./serviceInterfaces/ChatCompletionServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "ChatFeature",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      .product(name: "HighlightSwift", package: "highlightswift"),
      "AppEventServiceInterface",
      "AppFoundation",
      "AppUpdateServiceInterface",
      "ChatAppEvents",
      "ChatCompletionServiceInterface",
      "ChatFoundation",
      "ChatHistoryServiceInterface",
      "ChatServiceInterface",
      "CheckpointServiceInterface",
      "CodePreview",
      "ConcurrencyFoundation",
      "DLS",
      "ExtensionEventsInterface",
      "FileDiffFoundation",
      "FileDiffTypesFoundation",
      "FileIcon",
      "FileSuggestionServiceInterface",
      "FoundationInterfaces",
      "HighlighterServiceInterface",
      "JSONFoundation",
      "LLMFoundation",
      "LLMServiceInterface",
      "LocalServerServiceInterface",
      "LoggingServiceInterface",
      "Markdown",
      "PermissionsServiceInterface",
      "PushNotificationServiceInterface",
      "RoutingFoundation",
      "SettingsFeatureInterface",
      "SettingsServiceInterface",
      "SettingsServiceToolsAdapter",
      "SharedValuesFoundation",
      "ShellServiceInterface",
      "ThreadSafe",
      "ToolFoundation",
      "XcodeObserverServiceInterface",
    ],
    resources: [.process("Resources")],
    testsDependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      .product(name: "DependenciesTestSupport", package: "swift-dependencies"),
      "AccessibilityFoundation",
      "AppEventServiceInterface",
      "ChatAppEvents",
      "ChatCompletionServiceInterface",
      "ChatFeature",
      "ChatFoundation",
      "ChatHistoryServiceInterface",
      "ChatServiceInterface",
      "CheckpointServiceInterface",
      "ConcurrencyFoundation",
      "ExtensionEventsInterface",
      "FileSuggestionServiceInterface",
      "FoundationInterfaces",
      "JSONFoundation",
      "LLMFoundation",
      "LLMServiceInterface",
      "LocalServerServiceInterface",
      "SettingsServiceInterface",
      "SharedValuesFoundation",
      "SwiftTesting",
      "XcodeObserverServiceInterface",
    ],
    path: "./features/Chat/ChatFeature"))

targets.append(
  contentsOf: Target.module(
    name: "ChatFeatureInterface",
    path: "./features/Chat/ChatFeatureInterface"))

targets.append(
  contentsOf: Target.module(
    name: "ChatFoundation",
    dependencies: [],
    testsDependencies: [
      "ChatFoundation",
      "SwiftTesting",
    ],
    path: "./foundations/ChatFoundation"))

targets.append(
  contentsOf: Target.module(
    name: "ChatHistoryServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "CheckpointServiceInterface",
      "LLMServiceInterface",
      "LocalServerServiceInterface",
      "LoggingServiceInterface",
      "ThreadSafe",
      "ToolFoundation",
    ],
    testsDependencies: [
      "AppFoundation",
      "ChatHistoryServiceInterface",
      "ConcurrencyFoundation",
      "SwiftTesting",
    ],
    path: "./serviceInterfaces/ChatHistoryServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "ChatService",
    dependencies: [
      .product(name: "GRDB", package: "GRDB.swift"),
      "AppFoundation",
      "ChatHistoryServiceInterface",
      "ChatServiceInterface",
      "CheckpointServiceInterface",
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "FoundationInterfaces",
      "JSONFoundation",
      "LLMServiceInterface",
      "LocalServerServiceInterface",
      "LoggingServiceInterface",
      "ThreadSafe",
      "ToolFoundation",
    ],
    testsDependencies: [
      .product(name: "GRDB", package: "GRDB.swift"),
      "ChatHistoryServiceInterface",
      "ChatService",
      "ChatServiceInterface",
      "ConcurrencyFoundation",
      "FoundationInterfaces",
      "LLMServiceInterface",
      "SwiftTesting",
      "ToolFoundation",
    ],
    path: "./services/ChatService"))

targets.append(
  contentsOf: Target.module(
    name: "ChatServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "ThreadSafe",
      "ToolFoundation",
    ],
    path: "./serviceInterfaces/ChatServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "CheckpointService",
    dependencies: [
      "AppFoundation",
      "CheckpointServiceInterface",
      "DependencyFoundation",
      "JSONFoundation",
      "LocalServerServiceInterface",
    ],
    testsDependencies: [],
    path: "./services/CheckpointService"))

targets.append(
  contentsOf: Target.module(
    name: "CheckpointServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "ConcurrencyFoundation",
    ],
    testsDependencies: [
      "AppFoundation",
      "CheckpointServiceInterface",
      "ConcurrencyFoundation",
      "SwiftTesting",
    ],
    path: "./serviceInterfaces/CheckpointServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "ClaudeCodeTools",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      .product(name: "JSONScanner", package: "JSONScanner"),
      "AppFoundation",
      "ChatFoundation",
      "ChatServiceInterface",
      "ConcurrencyFoundation",
      "DLS",
      "FileIcon",
      "JSONFoundation",
      "LocalServerServiceInterface",
      "ShellServiceInterface",
      "ToolFoundation",
      "ToolTypesFoundation",
    ],
    testsDependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "ChatFoundation",
      "ClaudeCodeTools",
      "JSONFoundation",
      "SwiftTesting",
      "ToolFoundation",
    ],
    path: "./plugins/tools/ClaudeCodeTools"))

targets.append(
  contentsOf: Target.module(
    name: "CodeCompletionFeature",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AccessibilityFoundation",
      "AccessibilityObjCFoundation",
      "AppFoundation",
      "CodeCompletionFoundation",
      "CodeCompletionServiceInterface",
      "ConcurrencyFoundation",
      "DLS",
      "FileDiffFoundation",
      "FileDiffTypesFoundation",
      "FoundationInterfaces",
      "KeyboardShortcutServiceInterface",
      "LoggingServiceInterface",
      "RoutingFoundation",
      "SettingsServiceInterface",
      "ShellServiceInterface",
      "ThreadSafe",
      "XcodeControllerServiceInterface",
      "XcodeObserverServiceInterface",
      "XcodeObserverWindowsAdapter",
      "XcodeThemeFoundation",
    ],
    path: "./features/CodeCompletionFeature"))

targets.append(
  contentsOf: Target.module(
    name: "CodeCompletionFoundation",
    dependencies: [],
    path: "./foundations/CodeCompletionFoundation"))

targets.append(
  contentsOf: Target.module(
    name: "CodeCompletionService",
    dependencies: [
      "AccessibilityFoundation",
      "AppFoundation",
      "ChatAppEvents",
      "CodeCompletionFoundation",
      "CodeCompletionServiceInterface",
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "FileDiffFoundation",
      "FoundationInterfaces",
      "LLMFoundation",
      "LocalServerServiceInterface",
      "LoggingServiceInterface",
      "PermissionsServiceInterface",
      "SettingsServiceInterface",
      "SharedValuesFoundation",
      "ShellServiceInterface",
      "ThreadSafe",
      "XcodeControllerServiceInterface",
      "XcodeObserverServiceInterface",
    ],
    testsDependencies: [
      "AccessibilityFoundation",
      "AppFoundation",
      "CodeCompletionFoundation",
      "CodeCompletionService",
      "CodeCompletionServiceInterface",
      "ConcurrencyFoundation",
      "FileDiffFoundation",
      "FileDiffTypesFoundation",
      "FoundationInterfaces",
      "PermissionsServiceInterface",
      "SettingsServiceInterface",
      "ShellServiceInterface",
      "SwiftTesting",
      "ThreadSafe",
      "XcodeControllerServiceInterface",
      "XcodeObserverServiceInterface",
    ],
    path: "./services/CodeCompletionService"))

targets.append(
  contentsOf: Target.module(
    name: "CodeCompletionServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "CodeCompletionFoundation",
      "ConcurrencyFoundation",
      "FileDiffTypesFoundation",
      "SharedValuesFoundation",
      "ThreadSafe",
      "XcodeObserverServiceInterface",
    ],
    path: "./serviceInterfaces/CodeCompletionServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "CodePreview",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "ConcurrencyFoundation",
      "DLS",
      "FileDiffFoundation",
      "FileDiffTypesFoundation",
      "FileIcon",
      "FoundationInterfaces",
      "HighlighterServiceInterface",
      "LoggingServiceInterface",
      "XcodeControllerServiceInterface",
      "XcodeObserverServiceInterface",
    ],
    testsDependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "CodePreview",
      "ConcurrencyFoundation",
      "FileDiffFoundation",
      "FileDiffTypesFoundation",
      "FoundationInterfaces",
      "LoggingServiceInterface",
      "SettingsServiceInterface",
      "SwiftTesting",
      "XcodeControllerServiceInterface",
      "XcodeObserverServiceInterface",
    ],
    path: "./coreui/CodePreview"))

targets.append(
  contentsOf: Target.module(
    name: "ConcurrencyFoundation",
    dependencies: [],
    testsDependencies: [
      "ConcurrencyFoundation",
      "SwiftTesting",
    ],
    path: "./foundations/ConcurrencyFoundation"))

targets.append(
  contentsOf: Target.module(
    name: "DefaultToolView",
    dependencies: [
      "AppFoundation",
      "ConcurrencyFoundation",
      "DLS",
      "JSONFoundation",
      "LocalServerServiceInterface",
      "ToolFoundation",
    ],
    testsDependencies: [
      "DefaultToolView",
    ],
    path: "./coreui/DefaultToolView"))

targets.append(
  contentsOf: Target.module(
    name: "DependencyFoundation",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
    ],
    path: "./foundations/DependencyFoundation"))

targets.append(
  contentsOf: Target.module(
    name: "DLS",
    dependencies: [
      "AppFoundation",
      "ConcurrencyFoundation",
      "LoggingServiceInterface",
    ],
    resources: [
      .process("Resources/cmd-logo.svg"),
      .process("Resources/mcp.svg"),
    ],
    testsDependencies: [
      "DLS",
    ],
    path: "./coreui/DLS"))

targets.append(
  contentsOf: Target.module(
    name: "EditFilesTool",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "ChatServiceInterface",
      "CodePreview",
      "ConcurrencyFoundation",
      "DLS",
      "FileDiffFoundation",
      "FileDiffTypesFoundation",
      "FileIcon",
      "FoundationInterfaces",
      "JSONFoundation",
      "LocalServerServiceInterface",
      "LoggingServiceInterface",
      "ThreadSafe",
      "ToolFoundation",
      "ToolTypesFoundation",
      "XcodeControllerServiceInterface",
      "XcodeObserverServiceInterface",
    ],
    testsDependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      .product(name: "DependenciesTestSupport", package: "swift-dependencies"),
      "AppFoundation",
      "ChatServiceInterface",
      "CodePreview",
      "ConcurrencyFoundation",
      "EditFilesTool",
      "FileDiffFoundation",
      "FileDiffTypesFoundation",
      "FoundationInterfaces",
      "JSONFoundation",
      "SettingsServiceInterface",
      "SwiftTesting",
      "ToolFoundation",
      "XcodeControllerServiceInterface",
      "XcodeObserverServiceInterface",
    ],
    path: "./plugins/tools/EditFilesTool"))

targets.append(
  contentsOf: Target.module(
    name: "ExecuteCommandTool",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "CodePreview",
      "ConcurrencyFoundation",
      "DLS",
      "JSONFoundation",
      "LocalServerServiceInterface",
      "ShellServiceInterface",
      "ThreadSafe",
      "ToolFoundation",
      "ToolTypesFoundation",
    ],
    testsDependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "ConcurrencyFoundation",
      "ExecuteCommandTool",
      "LocalServerServiceInterface",
      "ShellServiceInterface",
      "SwiftTesting",
      "ToolFoundation",
    ],
    path: "./plugins/tools/ExecuteCommandTool"))

targets.append(
  contentsOf: Target.module(
    name: "ExtensionCommandHandler",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppEventServiceInterface",
      "ExtensionEventsInterface",
      "LoggingServiceInterface",
      "SharedValuesFoundation",
      "ShellServiceInterface",
      "XcodeObserverServiceInterface",
    ],
    path: "./plugins/ExtensionCommandHandler"))

targets.append(
  contentsOf: Target.module(
    name: "ExtensionEventsInterface",
    dependencies: [
      "AppEventServiceInterface",
      "AppFoundation",
      "LoggingServiceInterface",
      "SharedValuesFoundation",
      "ShellServiceInterface",
      "XcodeObserverServiceInterface",
    ],
    path: "./serviceInterfaces/ExtensionEventsInterface"))

targets.append(
  contentsOf: Target.module(
    name: "FileDiffFoundation",
    dependencies: [
      .product(name: "Algorithms", package: "swift-algorithms"),
      .product(name: "HighlightSwift", package: "highlightswift"),
      "AppFoundation",
      "FileDiffTypesFoundation",
      "LoggingServiceInterface",
    ],
    testsDependencies: [
      .product(name: "SnapshotTesting", package: "swift-snapshot-testing"),
      "AppFoundation",
      "FileDiffFoundation",
      "FileDiffTypesFoundation",
    ],
    testsExclude: ["__Snapshots__"],
    path: "./foundations/FileDiffFoundation"))

targets.append(
  contentsOf: Target.module(
    name: "FileDiffTypesFoundation",
    dependencies: [],
    path: "./foundations/FileDiffTypesFoundation"))

targets.append(
  contentsOf: Target.module(
    name: "FileIcon",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "ConcurrencyFoundation",
      "DLS",
      "FoundationInterfaces",
      "LocalServerServiceInterface",
      "ShellServiceInterface",
    ],
    resources: [
      .process("Resources/fileIcons"),
    ],
    path: "./coreui/FileIcon"))

targets.append(
  contentsOf: Target.module(
    name: "FileSuggestionService",
    dependencies: [
      .product(name: "Ifrit", package: "Ifrit"),
      "AppFoundation",
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "FileSuggestionServiceInterface",
      "ThreadSafe",
      "XcodeObserverServiceInterface",
    ],
    testsDependencies: [
      "ConcurrencyFoundation",
      "FileSuggestionService",
      "SwiftTesting",
      "XcodeObserverServiceInterface",
    ],
    path: "./services/FileSuggestionService"))

targets.append(
  contentsOf: Target.module(
    name: "FileSuggestionServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "ThreadSafe",
    ],
    testsDependencies: [],
    path: "./serviceInterfaces/FileSuggestionServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "FoundationInterfaces",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "JSONFoundation",
      "ThreadSafe",
    ],
    testsDependencies: [],
    path: "./foundations/FoundationInterfaces"))

targets.append(
  contentsOf: Target.module(
    name: "GithubCopilotFeature",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "DLS",
      "GithubCopilotFeatureInterface",
      "GithubCopilotServiceInterface",
      "RoutingFoundation",
    ],
    path: "./features/GithubCopilotFeature"))

targets.append(
  contentsOf: Target.module(
    name: "GithubCopilotFeatureInterface",
    dependencies: [
      "RoutingFoundation",
    ],
    path: "./featureInterfaces/GithubCopilotFeatureInterface"))

targets.append(
  contentsOf: Target.module(
    name: "GithubCopilotService",
    dependencies: [
      "AppFoundation",
      "CodeCompletionFoundation",
      "CodeCompletionServiceInterface",
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "FoundationInterfaces",
      "GithubCopilotServiceInterface",
      "JRPCServiceInterface",
      "JSONFoundation",
      "LoggingServiceInterface",
      "SettingsServiceInterface",
      "SharedValuesFoundation",
      "ShellServiceInterface",
      "ThreadSafe",
    ],
    resources: [
      .process("Resources/install-language-server.sh"),
    ],
    testsDependencies: [
      "AppFoundation",
      "CodeCompletionFoundation",
      "CodeCompletionServiceInterface",
      "ConcurrencyFoundation",
      "FoundationInterfaces",
      "GithubCopilotService",
      "GithubCopilotServiceInterface",
      "JRPCServiceInterface",
      "JSONFoundation",
      "LoggingServiceInterface",
      "ShellServiceInterface",
      "SwiftTesting",
    ],
    path: "./services/GithubCopilotService"))

targets.append(
  contentsOf: Target.module(
    name: "GithubCopilotServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "CodeCompletionFoundation",
      "CodeCompletionServiceInterface",
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "SharedValuesFoundation",
      "ThreadSafe",
    ],
    path: "./serviceInterfaces/GithubCopilotServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "HighlighterServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      .product(name: "HighlightSwift", package: "highlightswift"),
      "AppFoundation",
      "DependencyFoundation",
    ],
    path: "./serviceInterfaces/HighlighterServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "JRPCService",
    dependencies: [
      "AppFoundation",
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "JRPCServiceInterface",
      "LoggingServiceInterface",
    ],
    testsDependencies: [
      "JRPCService",
    ],
    path: "./services/JRPCService"))

targets.append(
  contentsOf: Target.module(
    name: "JRPCServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "ConcurrencyFoundation",
      "LoggingServiceInterface",
      "ThreadSafe",
    ],
    path: "./serviceInterfaces/JRPCServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "JSONFoundation",
    dependencies: [],
    testsDependencies: [],
    path: "./foundations/JSONFoundation"))

targets.append(
  contentsOf: Target.module(
    name: "KeyboardShortcutService",
    dependencies: [
      .product(name: "KeyboardShortcuts", package: "KeyboardShortcuts"),
      "DependencyFoundation",
      "KeyboardShortcutServiceInterface",
      "LoggingServiceInterface",
      "ThreadSafe",
      "XcodeObserverServiceInterface",
    ],
    path: "./services/KeyboardShortcutService"))

targets.append(
  contentsOf: Target.module(
    name: "KeyboardShortcutServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      .product(name: "KeyboardShortcuts", package: "KeyboardShortcuts"),
      "ThreadSafe",
    ],
    path: "./serviceInterfaces/KeyboardShortcutServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "LLMFoundation",
    dependencies: [
      "AppFoundation",
    ],
    testsDependencies: [
      "LLMFoundation",
    ],
    path: "./foundations/LLMFoundation"))

targets.append(
  contentsOf: Target.module(
    name: "LLMService",
    dependencies: [
      .product(name: "JSONScanner", package: "JSONScanner"),
      "AppFoundation",
      "ChatFoundation",
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "FoundationInterfaces",
      "JSONFoundation",
      "LLMFoundation",
      "LLMServiceInterface",
      "LocalServerServiceInterface",
      "LoggingServiceInterface",
      "SettingsServiceInterface",
      "ShellServiceInterface",
      "ThreadSafe",
      "ToolFoundation",
    ],
    testsDependencies: [
      .product(name: "DependenciesTestSupport", package: "swift-dependencies"),
      .product(name: "SnapshotTesting", package: "swift-snapshot-testing"),
      "AppFoundation",
      "ConcurrencyFoundation",
      "FoundationInterfaces",
      "JSONFoundation",
      "LLMFoundation",
      "LLMService",
      "LLMServiceInterface",
      "LocalServerServiceInterface",
      "SettingsServiceInterface",
      "ShellServiceInterface",
      "SwiftTesting",
      "ThreadSafe",
      "ToolFoundation",
    ],
    path: "./services/LLMService"))

targets.append(
  contentsOf: Target.module(
    name: "LLMServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "ChatFoundation",
      "ConcurrencyFoundation",
      "JSONFoundation",
      "LLMFoundation",
      "LocalServerServiceInterface",
      "SettingsServiceInterface",
      "ThreadSafe",
      "ToolFoundation",
    ],
    testsDependencies: [],
    path: "./serviceInterfaces/LLMServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "LocalServerService",
    dependencies: [
      "AppEventServiceInterface",
      "AppFoundation",
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "ExtensionEventsInterface",
      "FoundationInterfaces",
      "LocalServerServiceInterface",
      "LoggingServiceInterface",
      "SettingsServiceInterface",
      "ShellServiceInterface",
      "ThreadSafe",
    ],
    resources: [
      .process("Resources/build.sha256"),
      .process("Resources/launch-server.sh"),
      .process("Resources/main.bundle.cjs.gz"),
      .process("Resources/main.bundle.cjs.map"),
    ],
    testsDependencies: [
      "AppFoundation",
      "JSONFoundation",
      "LocalServerService",
      "LocalServerServiceInterface",
      "SwiftTesting",
    ],
    path: "./services/LocalServerService"))

targets.append(
  contentsOf: Target.module(
    name: "LocalServerServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "ConcurrencyFoundation",
      "JSONFoundation",
    ],
    testsDependencies: [
      "AppFoundation",
      "ConcurrencyFoundation",
      "LocalServerServiceInterface",
      "SwiftTesting",
    ],
    path: "./serviceInterfaces/LocalServerServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "LoggingService",
    dependencies: [
      .product(name: "Bugsnag", package: "bugsnag-cocoa"),
      .product(name: "Sentry", package: "sentry-cocoa"),
      .product(name: "Statsig", package: "statsig-kit"),
      "AppFoundation",
      "ConcurrencyFoundation",
      "FoundationInterfaces",
      "LoggingServiceInterface",
      "SettingsServiceInterface",
      "ThreadSafe",
    ],
    testsDependencies: [
      "ConcurrencyFoundation",
      "FoundationInterfaces",
      "LoggingService",
    ],
    path: "./services/LoggingService"))

targets.append(
  contentsOf: Target.module(
    name: "LoggingServiceInterface",
    dependencies: [
      "ConcurrencyFoundation",
      "FoundationInterfaces",
      "ThreadSafe",
    ],
    path: "./serviceInterfaces/LoggingServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "LSTool",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "ConcurrencyFoundation",
      "DLS",
      "FileIcon",
      "JSONFoundation",
      "LocalServerServiceInterface",
      "ToolFoundation",
      "ToolTypesFoundation",
    ],
    testsDependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "JSONFoundation",
      "LocalServerServiceInterface",
      "LSTool",
      "SwiftTesting",
      "ToolFoundation",
    ],
    path: "./plugins/tools/LSTool"))

targets.append(
  contentsOf: Target.module(
    name: "Markdown",
    dependencies: [
      .product(name: "Down", package: "Down"),
      "DLS",
      "LoggingServiceInterface",
    ],
    testsDependencies: [
      "Markdown",
    ],
    path: "./coreui/Markdown"))

targets.append(
  contentsOf: Target.module(
    name: "MCPService",
    dependencies: [
      .product(name: "MCP", package: "swift-sdk"),
      "AppFoundation",
      "ChatFoundation",
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "JRPCServiceInterface",
      "JSONFoundation",
      "LoggingServiceInterface",
      "MCPServiceInterface",
      "SettingsServiceInterface",
      "ShellServiceInterface",
      "ThreadSafe",
      "ToolFoundation",
    ],
    testsDependencies: [
      .product(name: "MCP", package: "swift-sdk"),
      "ConcurrencyFoundation",
      "JRPCServiceInterface",
      "JSONFoundation",
      "MCPService",
      "MCPServiceInterface",
      "SettingsServiceInterface",
      "ShellServiceInterface",
      "SwiftTesting",
      "ThreadSafe",
      "ToolFoundation",
    ],
    path: "./services/MCPService"))

targets.append(
  contentsOf: Target.module(
    name: "MCPServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "SettingsServiceInterface",
      "ThreadSafe",
      "ToolFoundation",
    ],
    path: "./serviceInterfaces/MCPServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "Onboarding",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "DLS",
      "FoundationInterfaces",
      "LLMServiceInterface",
      "LoggingServiceInterface",
      "PermissionsServiceInterface",
      "RoutingFoundation",
      "SettingsFeatureInterface",
      "SettingsServiceInterface",
    ],
    resources: [.process("Resources")],
    testsDependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      .product(name: "DependenciesTestSupport", package: "swift-dependencies"),
      "FoundationInterfaces",
      "LLMServiceInterface",
      "Onboarding",
      "PermissionsServiceInterface",
      "SettingsServiceInterface",
      "SwiftTesting",
    ],
    path: "./features/Onboarding"))

targets.append(
  contentsOf: Target.module(
    name: "PermissionsService",
    dependencies: [
      "AppFoundation",
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "FoundationInterfaces",
      "LoggingServiceInterface",
      "PermissionsServiceInterface",
      "ShellServiceInterface",
      "ThreadSafe",
    ],
    testsDependencies: [
      "ConcurrencyFoundation",
      "PermissionsService",
      "PermissionsServiceInterface",
      "ShellServiceInterface",
      "SwiftTesting",
    ],
    path: "./services/PermissionsService"))

targets.append(
  contentsOf: Target.module(
    name: "PermissionsServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "ConcurrencyFoundation",
      "ThreadSafe",
    ],
    testsDependencies: [
      "PermissionsServiceInterface",
      "SwiftTesting",
    ],
    path: "./serviceInterfaces/PermissionsServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "PushNotificationService",
    dependencies: [
      "DependencyFoundation",
      "LoggingServiceInterface",
      "PermissionsServiceInterface",
      "PushNotificationServiceInterface",
      "ThreadSafe",
    ],
    testsDependencies: [
      "PermissionsServiceInterface",
      "PushNotificationService",
      "PushNotificationServiceInterface",
      "SwiftTesting",
    ],
    path: "./services/PushNotificationService"))

targets.append(
  contentsOf: Target.module(
    name: "PushNotificationServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "ConcurrencyFoundation",
      "ThreadSafe",
    ],
    testsDependencies: [
      "PushNotificationServiceInterface",
      "SwiftTesting",
    ],
    path: "./serviceInterfaces/PushNotificationServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "ReadFileTool",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "ChatServiceInterface",
      "CodePreview",
      "ConcurrencyFoundation",
      "DLS",
      "FileIcon",
      "FoundationInterfaces",
      "HighlighterServiceInterface",
      "JSONFoundation",
      "LocalServerServiceInterface",
      "LoggingServiceInterface",
      "ThreadSafe",
      "ToolFoundation",
      "ToolTypesFoundation",
    ],
    testsDependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "FoundationInterfaces",
      "JSONFoundation",
      "ReadFileTool",
      "SwiftTesting",
      "ToolFoundation",
    ],
    path: "./plugins/tools/ReadFileTool"))

targets.append(
  contentsOf: Target.module(
    name: "RoutingFoundation",
    dependencies: [
      "AppFoundation",
    ],
    testsDependencies: [
      "RoutingFoundation",
    ],
    path: "./foundations/RoutingFoundation"))

targets.append(
  contentsOf: Target.module(
    name: "SearchFilesTool",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "ConcurrencyFoundation",
      "DLS",
      "FileIcon",
      "JSONFoundation",
      "LocalServerServiceInterface",
      "LoggingServiceInterface",
      "ToolFoundation",
      "ToolTypesFoundation",
    ],
    testsDependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "JSONFoundation",
      "LocalServerServiceInterface",
      "SearchFilesTool",
      "SwiftTesting",
      "ToolFoundation",
      "ToolTypesFoundation",
    ],
    path: "./plugins/tools/SearchFilesTool"))

targets.append(
  contentsOf: Target.module(
    name: "SettingsFeature",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AccessibilityFoundation",
      "AppFoundation",
      "AppUpdateServiceInterface",
      "ChatFoundation",
      "CodeCompletionServiceInterface",
      "ConcurrencyFoundation",
      "DLS",
      "ExtensionEventsInterface",
      "FoundationInterfaces",
      "GithubCopilotFeatureInterface",
      "LLMFoundation",
      "LLMServiceInterface",
      "LocalServerServiceInterface",
      "LoggingServiceInterface",
      "MCPService",
      "MCPServiceInterface",
      "PermissionsServiceInterface",
      "RoutingFoundation",
      "SettingsFeatureInterface",
      "SettingsServiceInterface",
      "SharedUtilsFoundation",
      "SharedValuesFoundation",
      "ShellServiceInterface",
      "ToolFoundation",
      "XcodeControllerServiceInterface",
      "XcodeObserverServiceInterface",
    ],
    testsDependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      .product(name: "DependenciesTestSupport", package: "swift-dependencies"),
      "ConcurrencyFoundation",
      "FoundationInterfaces",
      "LLMFoundation",
      "LLMServiceInterface",
      "SettingsFeature",
      "SettingsServiceInterface",
      "SwiftTesting",
    ],
    path: "./features/SettingsFeature"))

targets.append(
  contentsOf: Target.module(
    name: "SettingsFeatureInterface",
    dependencies: [
      "RoutingFoundation",
    ],
    path: "./featureInterfaces/SettingsFeatureInterface"))

targets.append(
  contentsOf: Target.module(
    name: "SettingsService",
    dependencies: [
      "AppFoundation",
      "ChatFoundation",
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "FoundationInterfaces",
      "JSONFoundation",
      "LLMFoundation",
      "LoggingServiceInterface",
      "SettingsServiceInterface",
      "SharedValuesFoundation",
      "ThreadSafe",
    ],
    testsDependencies: [
      "ConcurrencyFoundation",
      "FoundationInterfaces",
      "LLMFoundation",
      "SettingsService",
      "SettingsServiceInterface",
      "SharedValuesFoundation",
      "SwiftTesting",
    ],
    path: "./services/SettingsService"))

targets.append(
  contentsOf: Target.module(
    name: "SettingsServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "ConcurrencyFoundation",
      "JSONFoundation",
      "LLMFoundation",
      "LoggingServiceInterface",
    ],
    testsDependencies: [
      "LLMFoundation",
      "SettingsServiceInterface",
      "SwiftTesting",
    ],
    path: "./serviceInterfaces/SettingsServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "SettingsServiceToolsAdapter",
    dependencies: [
      "ChatFoundation",
      "SettingsServiceInterface",
      "ToolFoundation",
    ],
    testsDependencies: [
      "AppFoundation",
      "ChatFoundation",
      "ConcurrencyFoundation",
      "JSONFoundation",
      "SettingsServiceInterface",
      "SettingsServiceToolsAdapter",
      "SharedValuesFoundation",
      "SwiftTesting",
      "ToolFoundation",
    ],
    path: "./serviceAdapters/SettingsServiceToolsAdapter"))

targets.append(
  contentsOf: Target.module(
    name: "SharedUtilsFoundation",
    dependencies: [
      "LoggingServiceInterface",
    ],
    path: "./foundations/SharedUtilsFoundation"))

targets.append(
  contentsOf: Target.module(
    name: "SharedValuesFoundation",
    dependencies: [
      "FileDiffFoundation",
      "FileDiffTypesFoundation",
    ],
    path: "./foundations/SharedValuesFoundation"))

targets.append(
  contentsOf: Target.module(
    name: "ShellService",
    dependencies: [
      .product(name: "Subprocess", package: "swift-subprocess"),
      "AppFoundation",
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "LoggingServiceInterface",
      "ShellServiceInterface",
      "ThreadSafe",
    ],
    testsDependencies: [
      "ShellService",
    ],
    path: "./services/ShellService"))

targets.append(
  contentsOf: Target.module(
    name: "ShellServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "LoggingServiceInterface",
      "ThreadSafe",
    ],
    testsDependencies: [
      "ShellServiceInterface",
    ],
    path: "./serviceInterfaces/ShellServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "SwiftTesting",
    dependencies: [
      "AppFoundation",
      "ConcurrencyFoundation",
      "JSONFoundation",
    ],
    testsDependencies: [],
    path: "./foundations/SwiftTesting"))

targets.append(
  contentsOf: Target.macroModule(
    name: "ThreadSafe",
    macroDependencies: [
      .product(name: "SwiftCompilerPlugin", package: "swift-syntax"),
      .product(name: "SwiftSyntax", package: "swift-syntax"),
      .product(name: "SwiftSyntaxMacros", package: "swift-syntax"),
    ],
    dependencies: [
      .product(name: "SwiftCompilerPlugin", package: "swift-syntax"),
      .product(name: "SwiftSyntaxMacros", package: "swift-syntax"),
      "ConcurrencyFoundation",
    ],
    testsDependencies: [
      .product(name: "MacroTesting", package: "swift-macro-testing"),
      .product(name: "SwiftSyntax", package: "swift-syntax"),
      .product(name: "SwiftSyntaxMacros", package: "swift-syntax"),
      "ThreadSafeMacro",
    ],
    path: "./macros/ThreadSafe"))

targets.append(
  contentsOf: Target.module(
    name: "ToolFoundation",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "ChatFoundation",
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "JSONFoundation",
      "LoggingServiceInterface",
      "ThreadSafe",
    ],
    testsDependencies: [
      "AppFoundation",
      "ChatFoundation",
      "ConcurrencyFoundation",
      "JSONFoundation",
      "SwiftTesting",
      "ToolFoundation",
    ],
    path: "./foundations/ToolFoundation"))

targets.append(
  contentsOf: Target.module(
    name: "ToolTypesFoundation",
    dependencies: [
      "JSONFoundation",
    ],
    path: "./foundations/ToolTypesFoundation"))

targets.append(
  contentsOf: Target.module(
    name: "ToolUI",
    dependencies: [
      "AppFoundation",
      "DLS",
      "JSONFoundation",
      "Markdown",
      "ToolFoundation",
      "ToolTypesFoundation",
    ],
    path: "./coreui/ToolUI"))

targets.append(
  contentsOf: Target.module(
    name: "WebFetchTool",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      .product(name: "SwiftSoup", package: "SwiftSoup"),
      "AppFoundation",
      "ConcurrencyFoundation",
      "DLS",
      "JSONFoundation",
      "LLMServiceInterface",
      "LocalServerServiceInterface",
      "LoggingServiceInterface",
      "ToolFoundation",
      "ToolTypesFoundation",
    ],
    testsDependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppFoundation",
      "JSONFoundation",
      "SwiftTesting",
      "WebFetchTool",
    ],
    path: "./plugins/tools/WebFetchTool"))

targets.append(
  contentsOf: Target.module(
    name: "XcodeControllerService",
    dependencies: [
      .product(name: "XCLogParser", package: "XCLogParser"),
      "AppEventServiceInterface",
      "AppFoundation",
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "ExtensionEventsInterface",
      "FileDiffFoundation",
      "FoundationInterfaces",
      "LoggingServiceInterface",
      "SettingsServiceInterface",
      "SharedValuesFoundation",
      "ShellServiceInterface",
      "ThreadSafe",
      "XcodeControllerServiceInterface",
      "XcodeObserverServiceInterface",
    ],
    testsDependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AppEventServiceInterface",
      "AppFoundation",
      "ExtensionEventsInterface",
      "FileDiffFoundation",
      "FoundationInterfaces",
      "SettingsServiceInterface",
      "SharedValuesFoundation",
      "ShellServiceInterface",
      "SwiftTesting",
      "XcodeControllerService",
      "XcodeControllerServiceInterface",
      "XcodeObserverServiceInterface",
    ],
    path: "./services/XcodeControllerService"))

targets.append(
  contentsOf: Target.module(
    name: "XcodeControllerServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "FileDiffFoundation",
      "FileDiffTypesFoundation",
      "SettingsServiceInterface",
      "SharedValuesFoundation",
      "ThreadSafe",
    ],
    path: "./serviceInterfaces/XcodeControllerServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "XcodeObserverService",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      .product(name: "XcodeProj", package: "XcodeProj"),
      "AccessibilityFoundation",
      "AppFoundation",
      "ConcurrencyFoundation",
      "DependencyFoundation",
      "FoundationInterfaces",
      "LoggingServiceInterface",
      "PermissionsServiceInterface",
      "SettingsServiceInterface",
      "ShellServiceInterface",
      "ThreadSafe",
      "XcodeObserverServiceInterface",
    ],
    testsDependencies: [
      "ConcurrencyFoundation",
      "FoundationInterfaces",
      "LoggingServiceInterface",
      "PermissionsServiceInterface",
      "SettingsServiceInterface",
      "ShellServiceInterface",
      "SwiftTesting",
      "XcodeObserverService",
      "XcodeObserverServiceInterface",
    ],
    testsResources: [
      .copy("resources/"),
    ],
    path: "./services/XcodeObserverService"))

targets.append(
  contentsOf: Target.module(
    name: "XcodeObserverServiceInterface",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AccessibilityFoundation",
      "AppFoundation",
      "ConcurrencyFoundation",
      "FoundationInterfaces",
      "LoggingServiceInterface",
      "ThreadSafe",
    ],
    testsDependencies: [
      "XcodeObserverServiceInterface",
    ],
    path: "./serviceInterfaces/XcodeObserverServiceInterface"))

targets.append(
  contentsOf: Target.module(
    name: "XcodeObserverWindowsAdapter",
    dependencies: [
      .product(name: "Dependencies", package: "swift-dependencies"),
      "AccessibilityFoundation",
      "AccessibilityObjCFoundation",
      "XcodeObserverServiceInterface",
    ],
    path: "./serviceAdapters/XcodeObserverWindowsAdapter"))

targets.append(
  contentsOf: Target.module(
    name: "XcodeThemeFoundation",
    dependencies: [],
    path: "./foundations/XcodeThemeFoundation"))

targets.append(
  contentsOf: Target.module(
    name: "XPCServiceInterface",
    dependencies: [
      "ConcurrencyFoundation",
      "LoggingServiceInterface",
    ],
    path: "./serviceInterfaces/XPCServiceInterface"))

let package = Package(
  name: "Packages",
  platforms: [
    .macOS("15.0"),
  ],
  products: [
    .library(
      name: "App",
      targets: [
        "App",
      ]),
    .library(
      name: "AppExtension",
      targets: [
        "AppExtension",
      ]),
    .library(
      name: "AppLauncher",
      targets: [
        "AppLauncher",
      ]),
  ],
  dependencies: [
    .package(url: "https://github.com/appstefan/highlightswift", from: "1.1.0"),
    .package(
      url: "https://github.com/gsabran/Down",
      revision: "d2e9d901bbf9e7492a1603ed3dbf307c1089d7f2"),
    .package(url: "https://github.com/pointfreeco/swift-dependencies", from: "1.9.0"),
    .package(url: "https://github.com/sindresorhus/KeyboardShortcuts", from: "2.2.4"),
    .package(url: "https://github.com/tuist/XcodeProj", from: "9.1.0"),
    .package(url: "https://github.com/ukushu/Ifrit", from: "3.0.0"),
    .package(url: "https://github.com/swiftlang/swift-syntax", from: "602.0.0"),
    .package(url: "https://github.com/getsentry/sentry-cocoa", from: "8.56.0"),
    .package(url: "https://github.com/statsig-io/statsig-kit", from: "1.53.5"),
    .package(url: "https://github.com/sparkle-project/Sparkle", from: "2.7.0"),
    .package(
      url: "https://github.com/swiftlang/swift-subprocess",
      revision: "43f99d981c7486858b4bcb8cb5861e63bd63d841"),
    .package(url: "https://github.com/vapor/vapor.git", from: "4.115.1"),
    .package(url: "https://github.com/gsabran/JSONScanner", from: "1.0.0"),
    .package(url: "https://github.com/MobileNativeFoundation/XCLogParser", from: "0.2.41"),
    .package(url: "https://github.com/groue/GRDB.swift", from: "7.5.0"),
    .package(url: "https://github.com/bugsnag/bugsnag-cocoa", from: "6.32.2"),
    .package(url: "https://github.com/modelcontextprotocol/swift-sdk", from: "0.10.1"),
    .package(url: "https://github.com/scinfu/SwiftSoup.git", from: "2.11.1"),
    .package(url: "https://github.com/apple/swift-algorithms", from: "1.2.1"),

    // Testing dependencies:
    .package(url: "https://github.com/pointfreeco/swift-snapshot-testing", from: "1.18.7"),
    .package(url: "https://github.com/pointfreeco/swift-macro-testing", from: "0.6.4"),
  ],
  targets: targets)
