Target.module(
  name: "EditFilesTool",
  dependencies: [
    .product(name: "Dependencies", package: "swift-dependencies"),
    "AppFoundation",
    "ChatServiceInterface",
    "CodePreview",
    "ConcurrencyFoundation",
    "DLS",
    "FileDiffFoundation",
    "FileDiffTypesFoundation",
    "FileIcon",
    "FoundationInterfaces",
    "JSONFoundation",
    "LocalServerServiceInterface",
    "LoggingServiceInterface",
    "ThreadSafe",
    "ToolFoundation",
    "ToolTypesFoundation",
    "XcodeControllerServiceInterface",
    "XcodeObserverServiceInterface",
  ],
  testsDependencies: [
    .product(name: "Dependencies", package: "swift-dependencies"),
    .product(name: "DependenciesTestSupport", package: "swift-dependencies"),
    "AppFoundation",
    "ChatServiceInterface",
    "CodePreview",
    "ConcurrencyFoundation",
    "EditFilesTool",
    "FileDiffFoundation",
    "FileDiffTypesFoundation",
    "FoundationInterfaces",
    "JSONFoundation",
    "SettingsServiceInterface",
    "SwiftTesting",
    "ToolFoundation",
    "XcodeControllerServiceInterface",
    "XcodeObserverServiceInterface",
  ])
