Target.module(
  name: "EditFilesTool",
  dependencies: [
    "AppFoundation",
    "ChatServiceInterface",
    "CodePreview",
    "ConcurrencyFoundation",
    "DLS",
    "FileDiffFoundation",
    "FileDiffTypesFoundation",
    "FoundationInterfaces",
    "JSONFoundation",
    "ServerServiceInterface",
    "ThreadSafe",
    "ToolFoundation",
    "XcodeControllerServiceInterface",
    "XcodeObserverServiceInterface",
  ],
  testDependencies: [
    "AppFoundation",
    "CodePreview",
    "ConcurrencyFoundation",
    "FileDiffFoundation",
    "FoundationInterfaces",
    "JSONFoundation",
    "SwiftTesting",
    "ToolFoundation",
    "XcodeControllerServiceInterface",
  ])
