// swiftformat:disable all
// This file is generated by `yarn export-schema-swift`.
// Do not edit it manually.

import Foundation
import JSONFoundation

public enum Schema {}

extension KeyedDecodingContainer {
  /// Sugar syntax for decoding optional values without changing the type to be non optional.
  func decodeIfPresent<T: Decodable>(_ type: T?.Type, forKey key: KeyedDecodingContainer<K>.Key) throws -> T? {
    if contains(key) {
      return try decode(type, forKey: key)
    }
    return nil
  }
}
