Target.module(
  name: "XcodeObserverService",
  dependencies: [
    .product(name: "Dependencies", package: "swift-dependencies"),
    .product(name: "XcodeProj", package: "XcodeProj"),
    "AccessibilityFoundation",
    "AppFoundation",
    "ConcurrencyFoundation",
    "DependencyFoundation",
    "FoundationInterfaces",
    "LoggingServiceInterface",
    "PermissionsServiceInterface",
    "SettingsServiceInterface",
    "ShellServiceInterface",
    "ThreadSafe",
    "XcodeObserverServiceInterface",
  ],
  testsDependencies: [
    "ConcurrencyFoundation",
    "FoundationInterfaces",
    "LoggingServiceInterface",
    "PermissionsServiceInterface",
    "SettingsServiceInterface",
    "ShellServiceInterface",
    "SwiftTesting",
    "XcodeObserverService",
    "XcodeObserverServiceInterface",
  ],
  testsResources: [
    .copy("resources/"),
  ],
  interfaceDependencies: [
    .product(name: "Dependencies", package: "swift-dependencies"),
    "AccessibilityFoundation",
    "AppFoundation",
    "ConcurrencyFoundation",
    "FoundationInterfaces",
    "ThreadSafe",
  ])
