Target.module(
  name: "ChatInput",
  dependencies: [
    .product(name: "Dependencies", package: "swift-dependencies"),
    "AppFoundation",
    "ChatFoundation",
    "ChatHistoryServiceInterface",
    "CodePreview",
    "ConcurrencyFoundation",
    "DLS",
    "FileIcon",
    "FileSuggestionServiceInterface",
    "FoundationInterfaces",
    "LLMFoundation",
    "LLMServiceInterface",
    "LoggingServiceInterface",
    "RoutingFoundation",
    "SettingsFeatureInterface",
    "SettingsServiceInterface",
    "ToolFoundation",
    "XcodeObserverServiceInterface",
  ],
  testsDependencies: [
    .product(name: "Dependencies", package: "swift-dependencies"),
    "AccessibilityFoundation",
    "ChatHistoryServiceInterface",
    "ChatInput",
    "ConcurrencyFoundation",
    "FileSuggestionServiceInterface",
    "FoundationInterfaces",
    "LLMFoundation",
    "LLMServiceInterface",
    "SettingsServiceInterface",
    "SwiftTesting",
    "XcodeObserverServiceInterface",
  ])
