Target.module(
  name: "GithubCopilotService",
  dependencies: [
    "AppFoundation",
    "CodeCompletionFoundation",
    "ConcurrencyFoundation",
    "DependencyFoundation",
    "FoundationInterfaces",
    "GithubCopilotServiceInterface",
    "JRPCServiceInterface",
    "JSONFoundation",
    "LoggingServiceInterface",
    "SettingsServiceInterface",
    "ShellServiceInterface",
    "ThreadSafe",
  ],
  resources: [
    .process("Resources/install-language-server.sh"),
  ],
  testsDependencies: [
    "AppFoundation",
    "ConcurrencyFoundation",
    "FoundationInterfaces",
    "GithubCopilotService",
    "GithubCopilotServiceInterface",
    "JRPCServiceInterface",
    "JSONFoundation",
    "LoggingServiceInterface",
    "ShellServiceInterface",
    "SwiftTesting",
  ])
