Target.module(
  name: "InlineChatFeature",
  dependencies: [
    .product(name: "Dependencies", package: "swift-dependencies"),
    "AccessibilityFoundation",
    "AccessibilityObjCFoundation",
    "AppEventServiceInterface",
    "AppFoundation",
    "ChatAppEventsFoundation",
    "ChatFoundation",
    "ChatHistoryServiceInterface",
    "ChatInput",
    "ConcurrencyFoundation",
    "DLS",
    "FileDiffFoundation",
    "FileDiffTypesFoundation",
    "JSONFoundation",
    "LLMFoundation",
    "LLMServiceInterface",
    "LocalServerServiceInterface",
    "LoggingServiceInterface",
    "RoutingFoundation",
    "ToolFoundation",
    "XcodeControllerServiceInterface",
    "XcodeObserverServiceInterface",
    "XcodeObserverWindowsAdapter",
  ],
  testsDependencies: [])
