name: Main integration tests

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "**/*.md"
concurrency:
  group: main_${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
jobs:
  build_release_app:
    uses: ./.github/workflows/jobs/build-release-app.yml
    with:
      save_cache: true
      cache_key_suffix: main
    secrets: inherit

  test_swift_app:
    uses: ./.github/workflows/jobs/test-swift-app.yml
    with:
      save_cache: true
      cache_key_suffix: main
    secrets: inherit
